"""
Migration 0002 — Fix iShares and Global X ETF product page URLs
===============================================================
Replaces the generic issuer homepages with the specific product page
for each of the 55 iShares and 48 Global X ETFs listed in the database.
"""

ISHARES_URLS = {
    'AESG': 'https://www.blackrock.com/au/products/328186/ishares-global-aggregate-bond-esg-aud-hedged-etf',
    'AGGG': 'https://www.blackrock.com/au/products/346452/ishares-core-global-aggregate-bond-aud-hedged-etf',
    'ALTB': 'https://www.blackrock.com/au/products/337679/ishares-15+-year-australian-government-bond-etf',
    'AUMF': 'https://www.blackrock.com/au/products/284664/ishares-edge-msci-australia-multifactor-etf',
    'BILL': 'https://www.blackrock.com/au/products/287045/ishares-core-cash-etf',
    'EMXC': 'https://www.blackrock.com/au/products/337684/ishares-msci-emerging-markets-ex-china-etf',
    'GLDN': 'https://www.blackrock.com/au/products/332696/ishares-physical-gold-etf',
    'GLIN': 'https://www.blackrock.com/au/products/331650/ishares-core-ftse-global-infrastructure-aud-hedged-etf',
    'GLPR': 'https://www.blackrock.com/au/products/331647/ishares-core-ftse-global-property-ex-australia-aud-hedged-etf',
    'IAA':  'https://www.blackrock.com/au/products/273416/ishares-asia-50-etf',
    'IACT': 'https://www.blackrock.com/au/products/343627/ishares-u-s-factor-rotation-active-etf',
    'IAF':  'https://www.blackrock.com/au/products/251977/ishares-core-composite-bond-etf',
    'IBAL': 'https://www.blackrock.com/au/products/327628/ishares-balanced-esg-etf',
    'IBIT': 'https://www.blackrock.com/au/products/346455/ishares-bitcoin-etf',
    'ICME': 'https://www.blackrock.com/au/products/347181/ishares-credit-income-active-etf',
    'ICOR': 'https://www.blackrock.com/au/products/313534/ishares-core-corporate-bond-etf',
    'IEM':  'https://www.blackrock.com/au/products/273417/ishares-msci-emerging-markets-etf',
    'IESG': 'https://www.blackrock.com/au/products/318831/ishares-core-msci-australia-esg-etf',
    'IEU':  'https://www.blackrock.com/au/products/273427/ishares-europe-etf',
    'IGB':  'https://www.blackrock.com/au/products/251979/ishares-ubs-treasury-fund',
    'IGRO': 'https://www.blackrock.com/au/products/327642/ishares-high-growth-esg-etf',
    'IHCB': 'https://www.blackrock.com/au/products/275246/ishares-core-global-corporate-bond-aud-hedged-etf',
    'IHD':  'https://www.blackrock.com/au/products/251922/ishares-s-p-asx-dividend-opportunities-etf',
    'IHEB': 'https://www.blackrock.com/au/products/275254/ishares-j-p-morgan-usd-emerging-markets-bond-aud-hedged-etf',
    'IHHY': 'https://www.blackrock.com/au/products/275248/ishares-global-high-yield-bond-aud-hedged-etf',
    'IHOO': 'https://www.blackrock.com/au/products/271031/ishares-global-100-aud-hedged-etf',
    'IHQL': 'https://www.blackrock.com/au/products/335483/ishares-msci-world-ex-australia-quality-aud-hedged-etf',
    'IHVV': 'https://www.blackrock.com/au/products/271027/ishares-s-p-500-aud-hedged-etf',
    'IHWL': 'https://www.blackrock.com/au/products/283119/ishares-core-msci-world-ex-australia-esg-aud-hedged-etf',
    'IJH':  'https://www.blackrock.com/au/products/273425/ishares-s-p-mid-cap-etf',
    'IJP':  'https://www.blackrock.com/au/products/273434/ishares-msci-japan-etf',
    'IJR':  'https://www.blackrock.com/au/products/273426/ishares-s-p-small-cap-etf',
    'IKO':  'https://www.blackrock.com/au/products/273436/ishares-msci-south-korea-etf',
    'ILB':  'https://www.blackrock.com/au/products/251978/ishares-government-inflation-etf',
    'ILC':  'https://www.blackrock.com/au/products/251921/ishares-s-p-asx-20-etf',
    'IMTM': 'https://www.blackrock.com/au/products/335486/ishares-msci-world-ex-australia-momentum-etf',
    'IOO':  'https://www.blackrock.com/au/products/273428/ishares-global-100-etf',
    'IOZ':  'https://www.blackrock.com/au/products/251852/ishares-core-s-p-asx-200-etf',
    'IQLT': 'https://www.blackrock.com/au/products/335480/ishares-msci-world-ex-australia-quality-etf',
    'ISEC': 'https://www.blackrock.com/au/products/287042/ishares-enhanced-cash-etf',
    'ISO':  'https://www.blackrock.com/au/products/251923/ishares-s-p-asx-small-ordinaries-etf',
    'ITEK': 'https://www.blackrock.com/au/products/328189/ishares-nasdaq-top-30-etf',
    'IUSG': 'https://www.blackrock.com/au/products/331211/ishares-u-s-treasury-bond-aud-hedged-etf',
    'IVE':  'https://www.blackrock.com/au/products/273432/ishares-msci-eafe-etf',
    'IVV':  'https://www.blackrock.com/au/products/275304/ishares-s-p-500-etf',
    'IVHG': 'https://www.blackrock.com/au/products/335523/ishares-msci-world-ex-australia-value-aud-hedged-etf',
    'IVLU': 'https://www.blackrock.com/au/products/335478/ishares-msci-world-ex-australia-value-etf',
    'IWLD': 'https://www.blackrock.com/au/products/283117/ishares-core-msci-world-ex-australia-esg-etf',
    'IXI':  'https://www.blackrock.com/au/products/273429/ishares-global-consumer-staples-etf',
    'IXJ':  'https://www.blackrock.com/au/products/273430/ishares-global-healthcare-etf',
    'IYLD': 'https://www.blackrock.com/au/products/313537/ishares-yield-plus-etf',
    'IZZ':  'https://www.blackrock.com/au/products/273424/ishares-china-large-cap-etf',
    'MVOL': 'https://www.blackrock.com/au/products/284666/ishares-edge-msci-australia-minimum-volatility-etf',
    'ULTB': 'https://www.blackrock.com/au/products/339056/ishares-20+-year-u-s-treasury-bond-aud-hedged-etf',
    'WDMF': 'https://www.blackrock.com/au/products/284665/ishares-world-equity-factor-etf',
    'WVOL': 'https://www.blackrock.com/au/products/284667/ishares-msci-world-ex-australia-minimum-volatility-etf',
}

GLOBAL_X_URLS = {
    'A300':   'https://www.globalxetfs.com.au/funds/a300/',
    'ACDC':   'https://www.globalxetfs.com.au/funds/acdc/',
    'AINF':   'https://www.globalxetfs.com.au/funds/ainf/',
    'ATOM':   'https://www.globalxetfs.com.au/funds/atom/',
    'AYLD':   'https://www.globalxetfs.com.au/funds/ayld/',
    'BANK':   'https://www.globalxetfs.com.au/funds/bank/',
    'BCOM':   'https://www.globalxetfs.com.au/funds/bcom/',
    'BUGG':   'https://www.globalxetfs.com.au/funds/bugg/',
    'CURE':   'https://www.globalxetfs.com.au/funds/cure/',
    'DRGN':   'https://www.globalxetfs.com.au/funds/drgn/',
    'DTEC':   'https://www.globalxetfs.com.au/funds/dtec/',
    'EBTC':   'https://www.globalxetfs.com.au/funds/ebtc/',
    'EETH':   'https://www.globalxetfs.com.au/funds/eeth/',
    'ESTX':   'https://www.globalxetfs.com.au/funds/estx/',
    'ETPMAG': 'https://www.globalxetfs.com.au/funds/etpmag/',
    'ETPMPD': 'https://www.globalxetfs.com.au/funds/etpmpd/',
    'ETPMPM': 'https://www.globalxetfs.com.au/funds/etpmpm/',
    'ETPMPT': 'https://www.globalxetfs.com.au/funds/etpmpt/',
    'FANG':   'https://www.globalxetfs.com.au/funds/fang/',
    'FHNG':   'https://www.globalxetfs.com.au/funds/fhng/',
    'FTEC':   'https://www.globalxetfs.com.au/funds/ftec/',
    'GARP':   'https://www.globalxetfs.com.au/funds/garp/',
    'GHLD':   'https://www.globalxetfs.com.au/funds/ghld/',
    'GMTL':   'https://www.globalxetfs.com.au/funds/gmtl/',
    'GOLD':   'https://www.globalxetfs.com.au/funds/gold/',
    'GRPA':   'https://www.globalxetfs.com.au/funds/grpa/',
    'GXAI':   'https://www.globalxetfs.com.au/funds/gxai/',
    'GXLD':   'https://www.globalxetfs.com.au/funds/gxld/',
    'HGEN':   'https://www.globalxetfs.com.au/funds/hgen/',
    'J100':   'https://www.globalxetfs.com.au/funds/j100/',
    'LNAS':   'https://www.globalxetfs.com.au/funds/lnas/',
    'NDIA':   'https://www.globalxetfs.com.au/funds/ndia/',
    'OZXX':   'https://www.globalxetfs.com.au/funds/ozxx/',
    'PAVE':   'https://www.globalxetfs.com.au/funds/pave/',
    'QYLD':   'https://www.globalxetfs.com.au/funds/qyld/',
    'ROBO':   'https://www.globalxetfs.com.au/funds/robo/',
    'RSSL':   'https://www.globalxetfs.com.au/funds/rssl/',
    'SEMI':   'https://www.globalxetfs.com.au/funds/semi/',
    'SLVM':   'https://www.globalxetfs.com.au/funds/slvm/',
    'SNAS':   'https://www.globalxetfs.com.au/funds/snas/',
    'TECH':   'https://www.globalxetfs.com.au/funds/tech/',
    'U100':   'https://www.globalxetfs.com.au/funds/u100/',
    'USHY':   'https://www.globalxetfs.com.au/funds/ushy/',
    'USIG':   'https://www.globalxetfs.com.au/funds/usig/',
    'USTB':   'https://www.globalxetfs.com.au/funds/ustb/',
    'UYLD':   'https://www.globalxetfs.com.au/funds/uyld/',
    'WIRE':   'https://www.globalxetfs.com.au/funds/wire/',
    'ZYAU':   'https://www.globalxetfs.com.au/funds/zyau/',
    'ZYUS':   'https://www.globalxetfs.com.au/funds/zyus/',
}


def up(conn):
    for code, url in {**ISHARES_URLS, **GLOBAL_X_URLS}.items():
        conn.execute('UPDATE etfs SET issuer_url = ? WHERE code = ?', (url, code))
